### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by msphn** [bitExpert/disco#60]
Hey,

I'd like to suggest another way to provide application wide configuration and a second source for parameter injecting.

https://framework.zend.com/manual/2.4/en/modules/zend.config.introduction.html

Zend config encapsulates config into an object and provides getter, setter and methods to make config values readonly.

This could be pretty useful instead of using arrays. For example, if a config is not properly set an exception will be thrown. Error handling using a config structure like this could be improved. 

No need to use zend/config, but for me it's pretty nice and something similar or even zend/config could be helpful.

It also can parse config files as yaml, xml, json and so on, which is nice.
For example using zend/config get you could pass a second parameter as default.

I'm not sure how Parameters and Parameter annotations work at the moment and I didn't dig in, but would it work in general to make use of it?

If so and the idea sounds not bad I could try to implement it.

Regards

**Comment by shochdoerfer** [comment]
The problem I see is that there are a ton of different config mangement libs, each with a different implementation and their own "special" api. I do not want to build and maintain dozens of adapters just to please everyone. That's why currently we do only support arrays. As long as a 3rd party tool can spit out the configuration in array format or implement ArrayAccess everything is fine ;)

**Comment by shochdoerfer** [comment]
Currently I see no need to provide any other form of configuration format. Either make use of the default array or pick anything else that is able to return an array or implements ArrayAccess (e.g. vlucas/phpdotenv). The focus of Disco is not solving the configuration problem but the DI problem.
