### ISSUE TITLE
[Feature ]Automatically generate alias from return type declaration

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/disco#74]
Given you have bean method configuration that looks like this:
```php
/** @Bean({"alias" = "\My\Namespace\Service\ProductService"}) */
public function productService() : \My\Namespace\Service\ProductService
{
    return new \My\Namespace\Service\DefaultProductService();
}
```

The configured alias matches the return type definition - in this case either the name of an interface or a parent class. Since the alias is a hard-coded string it won't get updated during the usual refactorings (moving files to a different namespace and such) which is not what we want.

It would be nice to provide a sepcial keyword to let Disco automatically determine the return type declaration during the cached configuration generation process and automatically use the return type declaration as an alias, e.g.
```php
/** @Bean({"alias" = "type"}) */
public function productService() : \My\Namespace\Service\ProductService
{
    return new \My\Namespace\Service\DefaultProductService();
}
```

That way I could access the bean like this:
```
$beanFactory->get('\My\Namespace\Service\ProductService');
```

**Comment by codeliner** [comment]
@shochdoerfer I'd like to work on this issue. Do you have any hints for me where to start?

And I'd introduce a new Bean parameter instead of using alias = "type"

```php
** @Bean({"type_alias" = true}) */
public function productService() : \My\Namespace\Service\ProductService
{
    return new \My\Namespace\Service\DefaultProductService();
}
```

Or can we add it to Disco config so that Disco always generates the alias if it is enabled in the Disco config? We could still disable it for specific Beans with the annotation shown above.
What do you think?

**Comment by shochdoerfer** [comment]
Thanks for tackling this issue, I got so much other stuff on my plate that I am not able to get this going.

I am fine with the new parameter as long we find a way to allow just one of them the same time. I would assume that is solvable in [\bitExpert\Disco\Annotations\Bean::construct()](https://github.com/bitExpert/disco/blob/master/src/bitExpert/Disco/Annotations/Bean.php#L56) but I am not sure.

The main logic to store the aliases in the respective look-up table can be found in the [\bitExpert\Disco\Proxy\Configuration\ConfigurationGenerator](https://github.com/bitExpert/disco/blob/master/src/bitExpert/Disco/Proxy/Configuration/ConfigurationGenerator.php#L127). The current logic is rather simple: If an alias is not yet defined, simply add it to the array. For this feature you would need to get the type from the ReflectionMethod $method and then add it to the array of aliases.

**Comment by codeliner** [comment]
> I am fine with the new parameter as long we find a way to allow just one of them the same time.

Can I only have one alias per Bean or why should it not be possible to use both together?

What about the feature that you can enable type aliases for all Beans using a flag in the Disco config?

**Comment by shochdoerfer** [comment]
Right, we currently allow only one alias per bean definition and the first one found will win. A global flag would put us in a situation where we have to deal with conflicting aliases, e.g. 2 bean definitions returning the same type. Any idea how to solve that?

**Comment by codeliner** [comment]
> 2 bean definitions returning the same type.

Good catch! This should result in a meaningful exception. It would be the task of the user to resolve the conflict:
- deactivate type alias for effected Beans
- change return type to implementation not abstraction/interface

 > Right, we currently allow only one alias per bean definition

Oh, can we change that? Multiple aliases for the same Bean/Service is really useful.
example: 
My Event Machine defines services which should be available in the PSR-11 container: https://github.com/proophsoftware/event-machine/blob/master/src/EventMachine.php#L34

If I can only assign one alias to a service the rest of the application now needs to use the same alias instead of simply using `EventStore::class`
On the other hand I don't want to use `EventStore::class` as service id within Event Machine because there are maybe more than one event stores needed in the application.

**Comment by shochdoerfer** [comment]
Sure we can change that. The currently implementation is in place because I wanted Disco to be usable with Expressive. Your idea of multiple aliases definitely makes sense.

What about something like this then?
```
/**
 * @Bean({
 *     "singleton"=false,
 *     @Alias({"name" = "my_fixed_alias"}),
 *     @Alias({"name" = "my_fixed_alias2"}),
 *     @TypeAlias,
 * })
 */
```

TypeAlias could be a sub-annotation of Alias - speaking code-wise. The type resolving would still need to happen in the ConfigurationGenerator class as I don't think the annotation itself has access to the method it decorates.

**Comment by codeliner** [comment]
looks good. I try to come up with a PR the next days.

**Comment by shochdoerfer** [comment]
Great. If you need help, ping me.

**Comment by codeliner** [comment]
Unfortunately, the suggested syntax does not work. What works is:

```
/**
 * @Bean({
 *     "singleton"=false,
 *     "aliases"={
 *         @Alias({"name" = "my_fixed_alias"}),
 *         @Alias({"name" = "my_fixed_alias2"}),
 *         @TypeAlias,
 *     }
 * })
 */
```
or just: 

```
/**
 * @Bean({
 *     "singleton"=false,
 *     "aliases"={
 *         "my_fixed_alias",
 *          "my_fixed_alias2",
 *     },
 *     "typeAlias"=true
 * })
 */
```
First version looks nicer.
Second version is less stuff to write.

Thoughts?

And should we keep the current alias definition as a shorthand if user only wants to set one fixed alias?
It would keep BC at least for the annotations, but requires more documentation and is maybe confusing, because in theory this would be possible then:

```
/**
 * @Bean({
 *     "singleton"=false,
 *     "alias"="my_one_liner_alias",
 *     "aliases"={
 *         "my_fixed_alias",
 *          "my_fixed_alias2",
 *     },
 *     "typeAlias"=true
 * })
 */
```
We could throw an exception if "alias" is used together with "aliases" and/or "typeAlias" or merge all three, which would result in:
- my_one_liner_alias
- my_fixed_alias
- my_fixed_alias2
- My\ReturnType

**Comment by shochdoerfer** [comment]
I think I'd prefer this version even though it is more to type:
```
/**
 * @Bean({
 *     "singleton"=false,
 *     "aliases"={
 *         @Alias({"name" = "my_fixed_alias"}),
 *         @Alias({"name" = "my_fixed_alias2"}),
 *         @TypeAlias,
 *     }
 * })
 */
```
moving to this direction we could also - in separate PR - move the parameters definition inside the bean definition. I never really like the current separation and the parameters container needed, but it seems reasonable now with the change regarding the new "structure". Something like this could be the way to define a bean in the future:
```
/**
 * @Bean({
 *     "singleton"=false,
 *     "aliases"={
 *         @Alias({"name" = "my_fixed_alias"}),
 *         @Alias({"name" = "my_fixed_alias2"}),
 *         @TypeAlias,
 *     },
 *     "parameters"={
 *         @Parameter({"name" = "my_name1"}),
 *         @Parameter({"name" = "my_name2"})
 *     }
 * })
 */
```

Given that, it makes sense to me to get rid of the current alias attribute to provide consistency. BC breaks are not nice but I guess it is worth it in that regard. Aliases and parameter definitions are probably not used for each and every bean definition - at least in my experience - so changing your configuration after the upgrade should not be a big deal.
