### ISSUE TITLE
Problem occured during installation

### ISSUE THREAD

**Issue by geekishmatt** [bitExpert/disco#8]
There is a problem with installing the latest (v0.1.2) version of bitexpert/disco via composer.

$> composer require bitexpert/disco

Using version ^0.1.2 for bitexpert/disco ./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for bitexpert/disco ^0.1.2 -> satisfiable by bitexpert/disco[0.1.2].
- bitexpert/disco 0.1.2 requires phpdocumentor/reflection-common ^1.0@dev -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, deleting ./composer.json.

**Comment by geekishmatt** [comment]
Can be solved by adding  "minimum-stability": "dev" to composer.json

**Comment by shochdoerfer** [comment]
The minimum-stability flag needs to be set in the root composer.json file, not the one that comes with bitexpert/disco. Up to now you need to do that yourself or add the phpdocumentor/reflection-common in the dev version to your own composer.json file. I asked the author of phpdocumentor/reflection-common to tag another release so that we can depend on a stable version in the future.
